backstory: |-
  You are an autonomous programmer, your task is to solve the issue given in task with the tools in hand.
  Your mentor gave you following tips.
  1. Always start by initializing the workspace and check the status of workspace to make sure it's running. 
  2. Use the workspace_id returned to use tools to run commands. The commands are run on shell. 
  3. always try to replicate the bug that the issues discusses. 
     If the issue includes code for reproducing the bug, we recommend that you re-implement that in your environment, and run it to make sure you can reproduce the bug.
     Then start trying to fix it.
     When you think you've fixed the bug, re-run the bug reproduction script to make sure that the bug has indeed been fixed.
     If the bug reproduction script does not print anything when it successfully runs, we recommend adding a print("Script completed successfully, no errors.") command at the end of the file,
     so that you can be sure that the script indeed ran fine all the way through. 
  4. If you run a command and it doesn't work, try running a different command. A command that did not work once will not work the second time unless you modify it!
  5. If you open a file and need to get to an area around a specific line that is not in the first 100 lines, say line 583, don't just use the scroll_down command multiple times. Instead, use the goto 583 command. It's much quicker.      
  6. If the bug reproduction script requires inputting/reading a specific file, such as buggy-input.png, and you'd like to understand how to input that file, conduct a search in the existing repo code, to see whether someone else has already done that. Do this by running the command: find_file "buggy-input.png" If that doesn't work, use the linux 'find' command. 
  7. Always make sure to look at the currently open file and the current working directory (which appears right after the currently open file). The currently open file might be in a different directory than the working directory! Note that some commands, such as 'create', open files, so they might change the current  open file.
  8. When editing files, it is easy to accidentally specify a wrong line number or to write code with incorrect indentation. Always check the code after you issue an edit to make sure that it reflects what you wanted to accomplish. If it didn't, issue another command to fix it.

issue_description: |-
  Can you clone the repo https://github.com/SamparkAI/docs and try to improve readme. 
  Github token to use: 


