name: Run Examples Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'python/**'

jobs:
  test-examples:
    uses: ./.github/workflows/examples.yml
    with:
      working-directory: ./python
    secrets: inherit
